before_script:
  - php --version
  - echo "nodeJS "
  - node --version
  - echo "NPM "
  - npm --version
  - cd static
  - npm install

lint:
  script:
    - gulp js_lint
    - gulp php_lint

build:
  script:
    - gulp build
