stages:
  - setup
  - lint

before_script:
  - cd static

cache:
 paths:
   - static/node_modules/
   - php/vendor/

setup:
  stage: setup
  tags:
    - setup
  script:
    - npm install --quiet
    # - npm install -g git+https://git@github.com/gulpjs/gulp.git#4.0
    - cd ../php
    - composer install

lintJs:
  stage: lint
  tags:
    - lint
  script:
    - pwd
    - ls
    - ls node_modules
    - gulp --version
    - gulp js_lint

lintPHP:
  stage: lint
  tags:
    - lint
  script:
    - gulp php_lint
