stages:
  - setup
  - lint

before_script:
  - cd static

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - static/node_modules/

setup:
  stage: setup
  script:
    - npm install prune
    - npm install

lintJs:
  stage: lint
  tags:
    - lint
  script:
    - npm install update
    - gulp js_lint

lintPHP:
  stage: lint
  tags:
    - lint
  script:
    - gulp php_lint
