stages:
  - setup
  - lint

before_script:
  - cd static

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - static/node_modules/

setup:
  stage: setup
  tags:
    - setup
  script:
    - rm -rf node_modules
    - npm cache clean
    - npm prune
    - npm install

lintJs:
  stage: lint
  tags:
    - lint
  script:
    - gulp --version
    - gulp js_lint

lintPHP:
  stage: lint
  tags:
    - lint
  script:
    - gulp --version
    - gulp php_lint

test:
  stage: lint
  tags:
    - setup
  script:
    - ls node_modules
