stages:
  - setup
  - lint

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - static/node_modules/

setup:
  stage: setup
  script:
    - npm install --quiet

lintJs:
  stage: lint
  tags:
    - lint
  script:
    - static/gulp js_lint

lintPHP:
  stage: lint
  tags:
    - lint
  script:
    - static/gulp php_lint
